name: nonstationarities_test
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.8
  - atk-1.0=2.38.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - cairo=1.16.0
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - cryptography=38.0.3
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.8
  - gettext=0.21.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - graphite2=1.3.13
  - gst-plugins-base=1.21.2
  - gstreamer=1.21.2
  - gtk2=2.24.33
  - harfbuzz=5.3.0
  - icu=70.1
  - idna=3.4
  - jpeg=9e
  - lcms2=2.14
  - ld_impl_linux-64=2.39
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.14
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libglu=9.0.0
  - libgomp=12.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libzlib=1.2.13
  - ncurses=6.3
  - numpy=1.23.5
  - openjpeg=2.5.0
  - openssl=3.0.7
  - pango=1.50.12
  - pathlib2=2.3.7.post1
  - pcre2=10.40
  - pillow=9.2.0
  - pip=22.3.1
  - pixman=0.40.0
  - pthread-stubs=0.4
  - pycparser=2.21
  - pyopenssl=22.1.0
  - pypubsub=4.0.3
  - pysocks=1.7.1
  - python=3.9.15
  - python_abi=3.9
  - readline=8.1.2
  - requests=2.28.1
  - setuptools=65.5.1
  - six=1.16.0
  - tk=8.6.12
  - tzdata=2022f
  - urllib3=1.26.11
  - wheel=0.38.4
  - wxpython=4.2.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - absl-py==1.3.0
      - aiohttp==3.8.3
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.8
      - arabic-reshaper==2.1.4
      - arrow==1.2.3
      - asttokens==2.1.0
      - astunparse==1.6.3
      - async-lru==2.0.2
      - async-timeout==4.0.2
      - attrdict3==2.0.2
      - attrs==22.1.0
      - backcall==0.2.0
      - boto3==1.26.15
      - botocore==1.29.15
      - bravado==11.0.3
      - bravado-core==5.17.1
      - cachetools==5.2.0
      - click==8.1.3
      - contourpy==1.0.6
      - cycler==0.11.0
      - debugpy==1.6.3
      - decorator==4.4.2
      - distro==1.8.0
      - docker-pycreds==0.4.0
      - edit-distance==1.0.6
      - egi-pynetstation==0.0.0rc1
      - einops==0.6.0
      - entrypoints==0.4
      - esprima==4.0.1
      - et-xmlfile==1.1.0
      - executing==1.2.0
      - ffmpeg-python==0.2.0
      - ffpyplayer==4.3.5
      - filelock==3.8.0
      - fire==0.4.0
      - fonttools==4.38.0
      - fqdn==1.5.1
      - freetype-py==2.3.0
      - frozenlist==1.3.3
      - fsspec==2022.11.0
      - future==0.18.2
      - gevent==22.10.2
      - gitdb==4.0.9
      - gitpython==3.1.29
      - glfw==2.5.5
      - google-api-core==2.10.2
      - google-auth==2.14.1
      - google-auth-oauthlib==0.4.6
      - google-cloud==0.34.0
      - google-cloud-speech==2.16.2
      - googleapis-common-protos==1.57.0
      - greenlet==2.0.1
      - grpcio==1.50.0
      - grpcio-status==1.48.2
      - huggingface-hub==0.11.0
      - hydra-core==1.1.0
      - hydra-submitit-launcher==1.1.5
      - hyperpyyaml==1.1.0
      - imageio==2.22.4
      - imageio-ffmpeg==0.4.7
      - importlib-metadata==5.0.0
      - ipykernel==6.17.1
      - ipython==8.6.0
      - isoduration==20.11.0
      - jedi==0.18.2
      - jinja2==3.1.2
      - jmespath==1.0.1
      - joblib==1.2.0
      - json-tricks==3.16.1
      - jsonpointer==2.3
      - jsonref==1.0.1
      - jsonschema==4.17.0
      - jupyter-client==7.4.7
      - jupyter-core==5.0.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.6.0
      - jupyterlab==4.0.2
      - jupyterlab-server==2.23.0
      - kiwisolver==1.4.4
      - lightning-utilities==0.3.0
      - markdown==3.4.1
      - markdown-it-py==2.1.0
      - markupsafe==2.1.1
      - matplotlib==3.6.2
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - monotonic==1.6
      - more-itertools==9.0.0
      - moto==4.0.10
      - moviepy==1.0.3
      - msgpack==1.0.4
      - msgpack-numpy==0.4.8
      - multidict==6.0.2
      - neptune-client==0.16.12
      - nest-asyncio==1.5.6
      - notebook-shim==0.2.3
      - ntplib==0.4.0
      - numexpr==2.8.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - oauthlib==3.2.2
      - omegaconf==2.1.2
      - openpyxl==3.0.10
      - opt-einsum==3.3.0
      - packaging==21.3
      - pandas==1.5.1
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - platformdirs==2.5.4
      - proglog==0.1.10
      - prompt-toolkit==3.0.33
      - proto-plus==1.22.1
      - protobuf==3.20.3
      - psutil==5.9.4
      - psychopy==2022.2.4
      - psychtoolbox==3.0.18.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pygame==2.1.2
      - pyglet==1.4.11
      - pygments==2.13.0
      - pyjwt==2.6.0
      - pyparallel==0.2.2
      - pyparsing==3.0.9
      - pyqt5==5.15.7
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.11.0
      - pyrsistent==0.19.2
      - pyserial==3.5
      - python-bidi==0.4.2
      - python-dateutil==2.8.2
      - python-gitlab==3.11.0
      - python-speech-features==0.6
      - python-vlc==3.0.18121
      - python-xlib==0.32
      - pytorch-lightning==1.8.2
      - pytorch-warmup==0.1.1
      - pytz==2022.6
      - pyyaml==6.0
      - pyzmq==24.0.1
      - questplus==2019.4
      - regex==2022.10.31
      - requests-oauthlib==1.3.1
      - requests-toolbelt==0.10.1
      - responses==0.22.0
      - rfc3339-validator==0.1.4
      - rfc3987==1.3.8
      - rsa==4.9
      - ruamel-yaml==0.17.21
      - ruamel-yaml-clib==0.2.7
      - s3transfer==0.6.0
      - scikit-learn==1.1.3
      - scipy==1.9.3
      - sentencepiece==0.1.97
      - sentry-sdk==1.25.1
      - setproctitle==1.3.2
      - simplejson==3.18.0
      - smmap==5.0.0
      - sounddevice==0.4.5
      - soundfile==0.11.0
      - speechbrain==0.5.13
      - speechrecognition==3.8.1
      - stack-data==0.6.1
      - swagger-spec-validator==3.0.3
      - tables==3.7.0
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow-estimator==2.10.0
      - tensorflow-gpu==2.10.0
      - termcolor==2.1.1
      - threadpoolctl==3.1.0
      - tokenizers==0.13.2
      - toml==0.10.2
      - torch==1.13.0
      - torchaudio==0.13.0
      - torchmetrics==0.10.3
      - torchtext==0.14.0
      - tornado==6.2
      - tqdm==4.64.1
      #- traitlets==5.5.0
      - transformers==4.23.1
      - types-toml==0.10.8.1
      - typing-extensions==4.4.0
      - ujson==5.5.0
      - uri-template==1.2.0
      - wandb==0.15.4
      - wcwidth==0.2.5
      - webcolors==1.12
      - websocket-client==1.4.2
      - werkzeug==2.2.2
      - whisper==1.0
      - xarray==2022.11.0
      - xlrd==2.0.1
      - xmltodict==0.13.0
      - yarl==1.8.1
      - zipp==3.10.0
      - zope-event==4.5.0
      - zope-interface==5.5.2